import requests
import os
from dotenv import load_dotenv
load_dotenv()

SUPABASE_URL = "https://egyfupjorjczjfkmnusd.supabase.co"
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")  # Must use service role key

headers = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
}

sql_payload = {
    "query": """
    create table if not exists slack_messages (
      id bigint generated by default as identity primary key,
      sender text,
      channel_name text,
      message text,
      date timestamp
    );
    
    create table if not exists discord_messages (
      id bigint generated by default as identity primary key,
      sender text,
      channel_name text,
      message text,
      date timestamp
    );

    create table if not exists telegram_messages (
      id bigint generated by default as identity primary key,
      sender text,
      channel_name text,
      message text,
      date timestamp
    );
    """
}

response = requests.post(
    f"{SUPABASE_URL}/rest/v1/rpc/execute_sql", headers=headers, json=sql_payload
)

print("Response status:", response.status_code)
print("Response text:", response.text)
